version: 2
# Reference variables.
references:
  docker_default: &docker_10
    working_directory: /tmp/app
    docker:
      - image: node:10
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Taipei"

jobs:
  install:
    <<: *docker_10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-10-cache-{{checksum "yarn.lock"}}
            - node-10-cache
      - run:
          name: install dependencies
          command: |
            yarn config set cache-folder .yarn-cache
            yarn --frozen-lockfile
      - save_cache:
          key: node-10-cache-{{checksum "yarn.lock"}}
          paths:
            - .yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - node_modules
  lint:
    <<: *docker_10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run lint
          command: npm run lint
  test:
    <<: *docker_10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: npm run testonly:cov -- --no-cache --colors
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: junit.xml

workflows:
  version: 2
  lint-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install

